# makefile.darwin - your system-specific makefile for SIGPROC
BIN = /Users/sbates/Documents/Physics/Pulsars/hitrun/pipeline/code/git/sigproc
# edit this by hand if you want to change the C compiler options
CCC = gcc -O2 -g3

# The following optional libraries need to be edited by hand...
LPGPLOT =  -L/sw/lib/ -L/usr/X11R6/lib -Wl,-framework -Wl,Foundation  -lX11 -lpng -lz -lgfortran -laquaterm /Users/sbates/Documents/Physics/Pulsars/soft/ph-pipeline/packages/pgplot_5.2/pgplot/libpgplot.a /Users/sbates/Documents/Physics/Pulsars/soft/ph-pipeline/packages/pgplot_5.2/pgplot/libcpgplot.a
#LFITS = -L/Users/sbates/Documents/Physics/Pulsars/soft/ph-pipeline/packages/cfitsio_3.0/lib -lcfitsio
#LFFTW = -L//Users/sbates/Documents/Physics/Pulsars/soft/ph-pipeline/packages/fftw_3.1.2/lib -lfftw3 -lfftw3f
F77_LIBS = -lSystemStubs /Developer/SDKs/MacOSX10.3.9.sdk/usr/lib/gcc/darwin/2.95.2/libcc_dynamic.a
SUNLM = 
ifneq ($(origin LFITS), undefined)
	DFITS = -DPSRFITS
endif
ifneq ($(origin LFFTW), undefined)
	DFFTW = -DFFTW
	FFTWF = fftwdata.o
else
	FFTWF = fftwdummy.o
endif
%.o : %.f
	gfortran  -c $< -o $@
