/* prec.c */
double precess(double epoch_ra, double epoch_dec, double *ret_ra, double *ret_dec, double curtime, int src);
int sla_preces(char *system, double ep0, double ep1, double *ra, double *dc);
int sla_nut(double date, double rmatn[3][3]);
int sla_nutc(double date, double *dpsi, double *deps, double *eps0);
int sla_prec(double ep0, double ep1, double rmatp[3][3]);
int sla_prenut(double epoch, double date, double rmatpn[3][3]);
int sla_prebn(double bep0, double bep1, double rmatp[3][3]);
double sla_dranrm(double angle);
int sla_dcs2c(double a, double b, double v[3]);
double sla_epj(double date);
int sla_dmxm(double a[3][3], double b[3][3], double c[3][3]);
int sla_deuler(char *order, double phi, double theta, double psi, double rmat[3][3]);
int sla_dcc2s(double v[3], double *a, double *b);
int sla_dmxv(double dm[3][3], double va[3], double vb[3]);
int sla_addet(double rm, double dm, double eq, double *rc, double *dc);
int sla_etrms(double ep, double ev[3]);
int sla_fk45z(double r1950, double d1950, double bepoch, double *r2000, double *d2000);
int sla_map(double rm, double dm, double pr, double pd, double px, double rv, double eq, double date, double *ra, double *da);
int sla_mappa(double eq, double date, double amprms[21]);
int sla_evp(double date, double deqx, double dvb[3], double dpb[3], double dvh[3], double dph[3]);
int sla_dvn(double v[3], double uv[3], double *vm);
int sla_mapqk(double rm, double dm, double pr, double pd, double px, double rv, double amprms[21], double *ra, double *da);
double sla_epco(char *k0, char *k, double e);
double sla_epj2d(double epj);
double sla_epb2d(double epb);
double sla_epb(double date);
double sla_dvdv(double va[3], double vb[3]);
double current_time(void);
int isleap(int year);
int dysize(int yr);
